from django.contrib import admin
from .models import *

admin.site.register(Drug)
admin.site.register(ReportLogin)
admin.site.register(DoctorCategory)
admin.site.register(Doctor)
admin.site.register(DoctorSubCategory)
admin.site.register(Subscription)
admin.site.register(MedicalCollege)
admin.site.register(Student)
admin.site.register(Post)
admin.site.register(StudentPost)
admin.site.register(PostImage)
admin.site.register(StudentPostImage)
admin.site.register(PostLike)
admin.site.register(StudentPostLike)
admin.site.register(PostLike2)
admin.site.register(StudentPostLike2)
admin.site.register(Comment)
admin.site.register(StudentComment)
admin.site.register(Comment2)
admin.site.register(StudentComment2)
admin.site.register(ToolRequest)
admin.site.register(StudentSubscription)
admin.site.register(Notification)
admin.site.register(StudentNotification)
admin.site.register(Theme)
admin.site.register(ThemeRequest)
admin.site.register(SelectedTheme)
admin.site.register(History)
admin.site.register(StudentHistory)
admin.site.register(Saved)
admin.site.register(StudentSaved)
admin.site.register(Saved2)
admin.site.register(StudentSaved2)
admin.site.register(Patient)